sudo: False
language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - rpm
    - yum
    - createrepo_c
install:
  - pip install pybuilder
  - pyb install_dependencies
  - travis/build_createrepo_executable
script: "pyb -X"
