sudo: required
language: python
python:
  - "2.7"
install:
  - sudo apt-get install rpm yum createrepo
  - pip install coveralls
  - pip install pybuilder
  - pyb install_dependencies
script: "pyb -X"
after_success:
  - coveralls --verbose
