sudo: False
language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - rpm
    - yum
    - createrepo_c
install:
  - pip install pybuilder
  - pyb install_dependencies
  - mkdir $HOME/bin && cp travis/* $HOME/bin
  - echo $PATH
script: "pyb -X"
